# Create Custom Docker Image
# Pull tomcat latest image from dockerhub 
FROM tomcat:latest

# Maintainer
MAINTAINER "PR Reddy - dpt" 

# copy war file on to container 
COPY ./dpt.war /usr/local/tomcat/webapps